---
- hosts: k8s-worker-nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f || echo "Reset was not ok, but continuing"
     Reset was not ok, but continuingcat join_token | tail -2 > out.sh
     sh out.sh
